### ISSUE TITLE
Add Bennie and jets lyrics

### ISSUE THREAD

**Issue by tob** [tob/12barsongset#14]
Please find the lyrincs for Bernie and the jets of Elton John and add them to the app

**Comment by tob** [comment]
https://genius.com/Elton-john-bennie-and-the-jets-lyrics

**Comment by codewithnadeem14502** [comment]
can you assign me this please

**Comment by tob** [comment]
When doing this please verify in the browser that the songs is properly displayed

**Comment by codewithnadeem14502** [comment]
![Screenshot (308)](https://user-images.githubusercontent.com/105824474/195065439-d9f95fe6-2e96-4b5b-a6c9-9f0f4c65653b.png)
![Screenshot (309)](https://user-images.githubusercontent.com/105824474/195065463-8c61e27f-cc5f-43ab-b53e-ec49951f0f7e.png)
![Screenshot (310)](https://user-images.githubusercontent.com/105824474/195065557-99c6f75f-eaf4-4647-a093-5545994ef90e.png)
added in vs code , but the output is not correct ( that added song is not showing react live app ) 
can you help me this

**Comment by tob** [comment]
Strange because it looks good. In order to debug start small and then add more text. 

e.g. try just to add the basic object without all the lyrics:
`  {
    _id: "15",
    title: "Test",
    version: "tobia",
    order: 15,
    fontSize: 1,
    lyrics:'bla bla bla'
    }`
    
    if this works start adding the lyrics, I do suspect that your issue is between line 686 687 688, I think you have to put all of them on the same line. Look at the previous songs as example.

**Comment by codewithnadeem14502** [comment]
![Screenshot (313)](https://user-images.githubusercontent.com/105824474/195092411-5508ae93-1a62-42c6-97ae-ac73655bcf4a.png)

**Comment by tob** [comment]
try to visit your localhost in an incognito window. I do fear that you are seeing a cached version.

**Comment by tob** [comment]
I have tried and it works perfectly on my side so I am not sure about what your problem could be. Try to stop and restart the app and use incognito. (it is not necessary for me but I don't know your browser setup)

**Comment by codewithnadeem14502** [comment]
stilll same

**Comment by codewithnadeem14502** [comment]
??
