### ISSUE TITLE
Add Roxette lyrics

### ISSUE THREAD

**Issue by tob** [tob/12barsongset#15]
Please add the lyrics for Roxette of Dr.Feelgood to the list of songs.

https://www.google.com/search?q=roxette+dr.feelgood&oq=roxette+dr.feelgood&aqs=chrome..69i57j0i22i30l6j69i61.4201j0j7&sourceid=chrome&ie=UTF-8#wptab=si:AC1wQDCnZtfNUI2fl7K6t9yeOkKftycXbaAPkjjFcOiXQzcxEpVqSoS5a3NClkEeImCVa-4lIWbFpnUtQTKsEX9wk1l7f1-UrPvLYRQJ1vhxvxqH0Bnj6BcM2mOqY4vbkBTSe0jwUf8U5dyhNPI1tivXnYJO_Zw0POPETYSj2GjzurVcFmTkqpo%3D

**Comment by codewithnadeem14502** [comment]
can you assign me this please
