### ISSUE TITLE
Design favicon and logo

### ISSUE THREAD

**Issue by tob** [tob/12barsongset#5]
Currently I am using random images for favicon and logo, it would be nice to have something custom. It doesn't have to be anything special, even a simple coloured shape is good.

Acceptance criteria
Current assets are deleted and replaced with new custom ones.
The favicon does work and also all the other required logos for the various devices. (This is important to have the PWA behave properly and display a nice icon on devices)

**Comment by KaranSinghBisht** [comment]
Hey Tob, Can you elaborate on the type of logo you are looking for?

**Comment by codewithnadeem14502** [comment]
sir , please respond to it

**Comment by tob** [comment]
I just assigned it to you, thanks for the help

**Comment by codewithnadeem14502** [comment]
thank you sir

**Comment by codewithnadeem14502** [comment]
sir , i added the favicon but it is not wo
![Screenshot (285)](https://user-images.githubusercontent.com/105824474/194710469-da5521ed-3196-4aae-aea4-57af090a7d8e.png)
![Screenshot (286)](https://user-images.githubusercontent.com/105824474/194710473-fe563419-53db-4474-afd3-6b704980f9d7.png)
rking , i dont know why can you please help me

**Comment by codewithnadeem14502** [comment]
sir , i have raise a PR please check it
