### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by tob** [tob/12barsongset#6]
Update readme explaining how to run this app and what it is supposed to be.

I made this app to be able to have the songset displayed on a tablet when playing live with my band. This PWA is installed on the tablet of the singer that uses it to reorder his songs and read the lyrics.

The app makes the most of all the spaces available in the viewport by displaying the text in columns. 
It is also possible to increase and decrease the size of the lyrics to have them fitting the screen. 

This is a react app so the usual scripts should be described.

**Comment by codewithnadeem14502** [comment]
hello sir , i would like to work on this issue sir

**Comment by tob** [comment]
@codewithnadeem14502 this ticket is yours, looking forward for the PR!

**Comment by codewithnadeem14502** [comment]
sure , i will work on this , thank you for assigning me

**Comment by codewithnadeem14502** [comment]
Prerequisites
Before installation, please make sure you have already installed the following tools:

git
Nodejs

🛠️ Installation Steps
1)Fork the project
2)Clone the forked project
3)Navigate to the cloned project directory
4)Install the dependencies with npm install
5)Run npm run start to start the server



along with this i will add some screenshot of your project , that is enough ? or you want anything else

**Comment by tob** [comment]
Just keep or rewrite what there is in the readme and add what you suggested and this is going to be good to go! Thanks for the help

**Comment by codewithnadeem14502** [comment]
sir i am new to react , i dont know much about yarn , can you please help to get started , 
![Screenshot (257)](https://user-images.githubusercontent.com/105824474/194300055-09260b69-0b5a-4812-a115-a7fc2ad19280.png)

**Comment by tob** [comment]
@codewithnadeem14502 you should just run yarn before running yarn start.

yarn works as NPM so when you clone a new repo the first thing to do should be to install the dependencies by running `yarn`

once that finishes you should notice a node_modules folder created with all the dependencies. This means that now you can run `yarn start`

**Comment by tob** [comment]
Sorry for the delay in the answer but I am a bit slower because I'm sick in this days with flu 😓

**Comment by codewithnadeem14502** [comment]
> Sorry for the delay in the answer but I am a bit slower because I'm sick in this days with flu 😓
no problem sir , hope you will get well soon

**Comment by codewithnadeem14502** [comment]
sir

**Comment by codewithnadeem14502** [comment]
sir , please check now , i made the checks according to you , hope you like my work, thank you sir
